name: Build Talend Job

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb at-spi2-core libgtk-3-0 libxtst6 unzip

      - name: Download Talend Open Studio
        run: |
          wget https://github.com/advanova/talend-open-studio/releases/download/v8.0.1/TOS_DI-20211109_1610-V8.0.1.zip
          unzip TOS_DI-20211109_1610-V8.0.1.zip -d /opt/talend-tos
          chmod +x /opt/talend-tos/TOS_DI-20211109_1610-V8.0.1/TOS_DI-linux-gtk-x86_64

      - name: Clean OSGi configuration
        run: |
          sed -i \
            -e '/org.eclipse.compare.win32/d' \
            -e '/org.eclipse.jdt.launching.macosx/d' \
            -e '/org.eclipse.swt.win32.win32.x86_64/d' \
            -e '/org.eclipse.equinox.launcher.win32.win32.x86_64/d' \
            /opt/talend-tos/TOS_DI-20211109_1610-V8.0.1/configuration/config.ini

      - name: Configure OSGi bundles
        run: |
          sed -i 's/osgi.bundles=.*/osgi.bundles=org.eclipse.equinox.simpleconfigurator@1:start,org.eclipse.core.runtime@start,org.eclipse.equinox.common@2:start,org.eclipse.update.configurator@3:start/' /opt/talend-tos/TOS_DI-20211109_1610-V8.0.1/configuration/config.ini

      - name: Run Talend Build
        run: |
          xvfb-run -a -s "-screen 0 1024x768x24 -ac +extension GLX +render -noreset" \
            /opt/talend-tos/TOS_DI-20211109_1610-V8.0.1/TOS_DI-linux-gtk-x86_64 \
            -nosplash -consoleLog -data $GITHUB_WORKSPACE \
            -application org.talend.commandline.CommandLine \
            -cmd buildJob -job GroovyFind -output $GITHUB_WORKSPACE/build_output -format standalone

      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: talend-job
          path: |
            build_output/
            /opt/talend-tos/TOS_DI-20211109_1610-V8.0.1/configuration/*.log
