name: Build Talend Job

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'zulu'  # Using Zulu OpenJDK distribution

      - name: Download Talend Open Studio
        run: |
          wget https://github.com/advanova/talend-open-studio/releases/download/v8.0.1/TOS_DI-20211109_1610-V8.0.1.zip
          unzip TOS_DI-20211109_1610-V8.0.1.zip -d /opt/talend-tos
          chmod +x /opt/talend-tos/TOS_DI-20211109_1610-V8.0.1/TOS_DI-linux-gtk-x86_64

      - name: Set up Xvfb
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          Xvfb :99 -screen 0 1024x768x24 &
          export DISPLAY=:99

      - name: Debug Talend Installation
        run: |
          ls -l /opt/talend-tos/TOS_DI-20211109_1610-V8.0.1/
          ls -l /opt/talend-tos/TOS_DI-20211109_1610-V8.0.1/configuration/config.ini
          cat /opt/talend-tos/TOS_DI-20211109_1610-V8.0.1/configuration/config.ini

      - name: Run Talend Build
        run: |
          /opt/talend-tos/TOS_DI-20211109_1610-V8.0.1/TOS_DI-linux-gtk-x86_64 -nosplash -consoleLog -data $GITHUB_WORKSPACE -application org.talend.commandline.CommandLine -cmd buildJob -job GroovyFind -output $GITHUB_WORKSPACE/build_output -format standalone || echo "Talend build failed, check the log" && cat $GITHUB_WORKSPACE/.metadata/.log

      - name: Display Talend logs
        if: failure() # This step runs only if the previous one fails
        run: |
          echo "Talend Job Failed. Displaying the log:"
          cat $GITHUB_WORKSPACE/.metadata/.log
          ls

      - name: Package Job into Zip
        run: |
          zip -r talend_job_standalone.zip build_output/

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: talend-job-zip
          path: talend_job_standalone.zip
