name: Build Talend Job

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest  # Change to Windows for better compatibility with Talend GUI

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'zulu'  # Using Zulu OpenJDK distribution

    - name: Download Talend Open Studio
      run: |
        Invoke-WebRequest -Uri "https://github.com/advanova/talend-open-studio/releases/download/v8.0.1/TOS_DI-20211109_1610-V8.0.1.zip" -OutFile "TOS_DI-20211109_1610-V8.0.1.zip"
        Expand-Archive -Path "TOS_DI-20211109_1610-V8.0.1.zip" -DestinationPath "C:\opt\talend-tos"
        Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser
        Set-Location -Path "C:\opt\talend-tos\TOS_DI-20211109_1610-V8.0.1"

    - name: Run Talend Job
      run: |
        Start-Process "C:\opt\talend-tos\TOS_DI-20211109_1610-V8.0.1\TOS_DI-win-x86_64.exe" -ArgumentList "-nosplash", "-consoleLog", "-data", "$env:GITHUB_WORKSPACE", "-application", "org.talend.commandline.CommandLine", "-cmd", "buildJob", "-job", "GroovyFind", "-output", "$env:GITHUB_WORKSPACE\build_output", "-format", "standalone"
      continue-on-error: true # This ensures the job doesn't stop if the error happens

    - name: Display Talend logs
      if: failure() # This step runs only if the previous one fails
      run: |
        echo "Talend Job Failed. Displaying the log:"
        Get-Content "$env:GITHUB_WORKSPACE\.metadata\.log"
        dir

    - name: Package Job into Zip
      run: |
        Compress-Archive -Path "build_output/*" -DestinationPath "talend_job_standalone.zip"

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: talend-job-zip
        path: talend_job_standalone.zip
