name: Build Talend Job

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'zulu'  # Using Zulu OpenJDK distribution

    - name: Download Talend Open Studio
      run: |
<<<<<<< HEAD
        Invoke-WebRequest -Uri "https://github.com/advanova/talend-open-studio/releases/download/v8.0.1/TOS_DI-20211109_1610-V8.0.1.zip" -OutFile "TOS_DI-20211109_1610-V8.0.1.zip"
        Expand-Archive -Path "TOS_DI-20211109_1610-V8.0.1.zip" -DestinationPath "C:\opt\talend-tos"
        Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser
        Set-Location -Path "C:\opt\talend-tos\TOS_DI-20211109_1610-V8.0.1"
=======
        wget https://github.com/advanova/talend-open-studio/releases/download/v8.0.1/TOS_DI-20211109_1610-V8.0.1.zip
        unzip TOS_DI-20211109_1610-V8.0.1.zip -d /opt/talend-tos
        chmod +x /opt/talend-tos/TOS_DI-20211109_1610-V8.0.1/TOS_DI-linux-gtk-x86_64
>>>>>>> parent of 5c47c3d... Update build.yml

  # Run Talend build job
    - name: Run Talend Job
      run: |
<<<<<<< HEAD
        Start-Process "C:\opt\talend-tos\TOS_DI-20211109_1610-V8.0.1\TOS_DI-win-x86_64.exe" -ArgumentList "-nosplash", "-consoleLog", "-data", "$env:GITHUB_WORKSPACE", "-application", "org.talend.commandline.CommandLine", "-cmd", "buildJob", "-job", "GroovyFind", "-output", "$env:GITHUB_WORKSPACE\build_output", "-format", "standalone"
=======
        sudo apt-get install xvfb
        Xvfb :99 -screen 0 1024x768x24 &
        export DISPLAY=:99
        /opt/talend-tos/TOS_DI-20211109_1610-V8.0.1/TOS_DI-linux-gtk-x86_64 -nosplash -consoleLog -data $GITHUB_WORKSPACE -application org.talend.commandline.CommandLine -cmd buildJob -job GroovyFind -output $GITHUB_WORKSPACE/build_output -format standalone || echo "Talend build failed, check the log" && cat $GITHUB_WORKSPACE/.metadata/.log
>>>>>>> parent of 5c47c3d... Update build.yml
      continue-on-error: true # This ensures the job doesn't stop if the error happens

      # Display the log if the Talend job fails
    - name: Display Talend logs
      if: failure() # This step runs only if the previous one fails
      run: |
        echo "Talend Job Failed. Displaying the log:"
        cat $GITHUB_WORKSPACE/.metadata/.log
        ls
    - name: Package Job into Zip
      run: |
        zip -r talend_job_standalone.zip build_output/

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: talend-job-zip
        path: talend_job_standalone.zip
