name: Build Talend Job

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: [self-hosted, Windows]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb libgtk-3-0 libxtst6 unzip libcanberra-gtk3-module \
                                  libxkbcommon-x11-0 libdbus-glib-1-2 libcanberra-gtk-module \
                                  x11-utils dbus-x11

      - name: Download Talend
        run: |
          wget -q https://github.com/advanova/talend-open-studio/releases/download/v8.0.1/TOS_DI-20211109_1610-V8.0.1.zip
          unzip -q TOS_DI-20211109_1610-V8.0.1.zip -d /opt/talend-tos
          chmod +x /opt/talend-tos/TOS_DI-20211109_1610-V8.0.1/TOS_DI-linux-gtk-x86_64

      - name: Backup and Modify OSGi Config
        run: |
          CONFIG_FILE="/opt/talend-tos/TOS_DI-20211109_1610-V8.0.1/configuration/config.ini"
          cp "$CONFIG_FILE" "${CONFIG_FILE}.bak"  # Backup

          sed -i \
            -e '/win32/d' \
            -e '/macosx/d' \
            "$CONFIG_FILE"

          sed -i 's|osgi.bundles=.*|osgi.bundles=org.eclipse.equinox.simpleconfigurator@1:start,org.eclipse.core.runtime@2:start,org.eclipse.equinox.common@3:start,org.eclipse.update.configurator@4:start,org.eclipse.core.resources@5:start,org.eclipse.equinox.preferences@6:start,org.eclipse.core.runtime@7:start|' \
            "$CONFIG_FILE"

      - name: Start Xvfb and Verify Display
        run: |
          export DISPLAY=:99
          Xvfb $DISPLAY -screen 0 1920x1080x24 +extension GLX -nolisten tcp -noreset &
          sleep 5
          xdpyinfo -display :99 || (echo "Xvfb failed to start" && exit 1)  # Ensure Xvfb is running

      - name: Clean Talend Configuration
        run: |
          rm -rf /opt/talend-tos/TOS_DI-20211109_1610-V8.0.1/configuration/org.eclipse.osgi

      - name: Force Eclipse to Rebuild Plugin Cache
        run: |
          /opt/talend-tos/TOS_DI-20211109_1610-V8.0.1/TOS_DI-linux-gtk-x86_64 \
          -clean -initialize

      - name: Run Talend Build with Debugging
        run: |
          export DISPLAY=:99
          
          /opt/talend-tos/TOS_DI-20211109_1610-V8.0.1/TOS_DI-linux-gtk-x86_64 \
            -nosplash -consoleLog -debug -data $GITHUB_WORKSPACE \
            -application org.talend.commandline.CommandLine \
            -cmd buildJob -job GroovyFind -output /opt/build_output -format standalone || \
          (cat /opt/talend-tos/TOS_DI-20211109_1610-V8.0.1/configuration/*.log && exit 1)

      - name: Archive Artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: build-artifacts
          path: |
            /opt/build_output/
            /opt/talend-tos/TOS_DI-20211109_1610-V8.0.1/configuration/*.log
