name: Build Talend Job

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb libgtk-3-0 libxtst6 unzip libcanberra-gtk3-module libxkbcommon-x11-0 libwebkit2gtk-4.0-37 libxslt1.1

      - name: Download Talend
        run: |
          wget -q https://github.com/advanova/talend-open-studio/releases/download/v8.0.1/TOS_DI-20211109_1610-V8.0.1.zip
          unzip -q TOS_DI-20211109_1610-V8.0.1.zip -d /opt/talend-tos
          chmod +x /opt/talend-tos/TOS_DI-20211109_1610-V8.0.1/TOS_DI-linux-gtk-x86_64

      - name: Clean OSGi config
        run: |
          sed -i \
            -e '/win32/d' \
            -e '/macosx/d' \
            /opt/talend-tos/TOS_DI-20211109_1610-V8.0.1/configuration/config.ini

      - name: Configure core bundles
        run: |
          sed -i 's/osgi.bundles=.*/osgi.bundles=org.eclipse.equinox.simpleconfigurator@1:start,org.eclipse.core.runtime@2:start,org.eclipse.equinox.common@3:start,org.eclipse.update.configurator@4:start,org.eclipse.core.resources@5:start,org.eclipse.equinox.preferences@6:start/' \
            /opt/talend-tos/TOS_DI-20211109_1610-V8.0.1/configuration/config.ini

      - name: Run Talend build
        run: |
          export DISPLAY=:99
          Xvfb $DISPLAY -screen 0 1920x1080x24 +extension GLX -nolisten tcp -noreset &
          sleep 30  # Increased wait period
          
          /opt/talend-tos/TOS_DI-20211109_1610-V8.0.1/TOS_DI-linux-gtk-x86_64 \
            -nosplash -consoleLog -data $GITHUB_WORKSPACE \
            -application org.talend.commandline.CommandLine \
            -cmd buildJob -job GroovyFind -output $GITHUB_WORKSPACE/build_output -format standalone -debug

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: build-artifacts
          path: |
            build_output/
            /opt/talend-tos/TOS_DI-20211109_1610-V8.0.1/configuration/*.log
