name: Build Talend Job

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: [self-hosted, Windows]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up JDK
      run : |
        $env:PATH = "C:\Tools\jdk-11.0.19_windows-x64_bin\jdk-11.0.19\bin;" + $env:PATH
        java -version  # Verify the Java version

    - name: Run Talend Job
      run: |
        Start-Process "C:\SandBox\MAIF\TOS_DI-20160912_1228-V6.1.2\TOS_DI-win-x86_64.exe" -ArgumentList "-nosplash", "-consoleLog", "-data", "$env:GITHUB_WORKSPACE\GroovyFinder\GroovyFinder", "-application", "org.talend.commandline.CommandLine", "-cmd", "buildJob", "-job", "GroovyFind", "-output", "$env:GITHUB_WORKSPACE\build_output", "-format", "standalone"
      continue-on-error: true # This ensures the job doesn't stop if the error happens

    - name: Display Talend logs
      if: failure() # This step runs only if the previous one fails
      run: |
        echo "Talend Job Failed. Displaying the log:"
        Get-Content "$env:GITHUB_WORKSPACE\.metadata\.log"
        dir

    - name: Package Job into Zip
      run: |
        Compress-Archive -Path "build_output/*" -DestinationPath "talend_job_standalone.zip"

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: talend-job-zip
        path: talend_job_standalone.zip
